baseURL: https://139.155.239.250/
title: Note
theme: hugo-tl
defaultContentLanguage: zh-cn
languageCode: zh-cn

copyright: copyright@

enableEmoji: true
hasCJKLanguage: true

paginate: 9

summaryLength: 15  # 摘要长度

uglyURLs: false  # 默认 false ；启用时，创建的 URL 格式是 /filename.html 而不是 /filename/