baseURL: https://139.155.239.250/
title: Note
theme: hugo-tl
defaultContentLanguage: zh-cn
languageCode: zh-cn

copyright: copyright@

enableEmoji: true
hasCJKLanguage: true

paginate: 9

build:
  noJSConfigInAssets: true