baseURL: https://139.155.239.250/
title: Note
theme: hugo-tl
defaultContentLanguage: zh-cn
languageCode: zh-cn

copyright: copyright@

enableEmoji: true
hasCJKLanguage: true

paginate: 9

menu:
  main:
  - identifier: categories
    name: 分类
    pre: icon-guidang
    url: /categories/
    weight: -70
  - identifier: tags
    name: 标签
    pre: icon-24gl-tags2
    url: /tags/
    weight: -60
  - identifier: about
    name: 关于
    pre: icon-shouye
    url: /about/
    weight: -50
  - identifier: search
    name: 搜索
    pre: icon-sousuo
    url: /search/
    weight: -40

build:
  noJSConfigInAssets: true  

params:
  AuthorName: lei
  subtitle: "每天八杯水"
  dateFormat : 2006-01-02
  enableCat: true
  cdnEnable: false  #是否启用cdn加速  data/external.yaml 中配置
  toc: true
  rssFullContent: true   # rss是否包含正文内容

markup:
    defaultMarkdownHandler: goldmark
    # parser:
    #   attribute:
    #     block: true
    #     title: true
    #   autoHeadingID: true
    #   autoHeadingIDType: github
    goldmark:
        renderer:
            unsafe: true
    # https://xyproto.github.io/splash/docs/
    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: false
        noClasses: true
        noHl: false
        style: friendly
        # style: native
        tabWidth: 2
    tableOfContents:
        endLevel: 4
        startLevel: 2