version: '1.0'
name: pipeline-20240704
displayName: pipeline-20240704
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-ffbb05aa
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: '1'
          hostID:
            - 11feac5b-03d2-4630-96ae-15821f45b788
        script:
          - '# 请在此输入您想执行的脚本'
          - cd /root/note_hugo/
          - '# 更新'
          - echo '-----更新源文件 start-----'
          - git pull
          - echo '-----更新源文件 end-----'
          - if [ -d "/root/note_hugo/public/" ];then
          - "\trm -rf /root/note_hugo/public/"
          - fi
          - echo '-----更新依赖 start-----'
          - '# 构建'
          - npm install
          - echo '-----更新依赖 end-----'
          - echo '-----构建 start-----'
          - '# 构建'
          - npm run build
          - echo '-----构建 end-----'
          - ''
          - rm -rf /usr/local/nginx/html/*
          - mv /root/note_hugo/public/* /usr/local/nginx/html/
          - ''
          - echo 'Success!!!'
        notify: []
        strategy:
          retry: '0'
