version: '1.0'
name: pipeline-20240704
displayName: pipeline-20240704
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-ffbb05aa
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID:
          ID: '1'
          hostID:
            - 11feac5b-03d2-4630-96ae-15821f45b788
        script:
          - '# 请在此输入您想执行的脚本'
          - cd /root/note_hugo/
          - '# 更新'
          - git pull
          - '# 删除原有文件'
          - rm -rf /usr/local/nginx/html/*
          - '# 构建'
          - npm run build
          - '# 将新的文件移动到网站根目录'
          - mv /root/note_hugo/public/* /usr/local/nginx/html/
          - '#删除构建产物'
          - rm -rf /root/note_hugo/public/*
        notify: []
        strategy:
          retry: '0'
