baseURL: http://192.168.73.73:8000/
title: Note
theme: hugo-theme
defaultContentLanguage: zh-cn
languageCode: zh-cn

copyright: copyright-@

enableEmoji: true
hasCJKLanguage: true

paginate: 3

menu:
  main:
  - identifier: 归档
    name: archives
    pre: <i class='fa fa-heart'></i>
    url: /archives/
    weight: -70
  - identifier: 标签
    name: tags
    pre: <i class='fa fa-heart'></i>
    url: /tags/
    weight: -60
  - identifier: about
    name: about
    pre: <i class='fa fa-heart'></i>
    url: /about/
    weight: -50
  

params:
  AuthorName: lei
  GitHubUser: spf13
  subtitle: "每天八杯水"
  dateFormat : 2006-01-02

markup:
    defaultMarkdownHandler: goldmark
    # parser:
    #   attribute:
    #     block: true
    #     title: true
    #   autoHeadingID: true
    #   autoHeadingIDType: github
    goldmark:
        renderer:
            unsafe: true
    # https://xyproto.github.io/splash/docs/
    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: false
        noClasses: true
        noHl: false
        style: github
        # style: native
        tabWidth: 2
    tableOfContents:
        endLevel: 3
        startLevel: 1